image: mcr.microsoft.com/dotnet/sdk:9.0

stages:
  - build
  - test
  - publish
  - deploy

variables:
  PROJECT_NAME: "Prod"
  TEST_PROJECT_NAME: "Prod.Tests"
  TEST_INTG_PROJECT_NAME: "Prod.Tests.Integration"
  BUILD_CONFIGURATION: "Release"
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_TLS_VERIFY: "1"
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_DRIVER: overlay2

build:
  stage: build
  script:
    - echo "Restoring dependencies..."
    - dotnet restore $PROJECT_NAME
    - echo "Building the project..."
    - dotnet build $PROJECT_NAME --configuration $BUILD_CONFIGURATION --no-restore
  artifacts:
    paths:
      - $PROJECT_NAME/bin/$BUILD_CONFIGURATION/net9.0/
    expire_in: 1 week

test:
  stage: test
  script:
    - echo "Running unit tests..."
    - dotnet test $TEST_PROJECT_NAME --configuration $BUILD_CONFIGURATION --no-build
    - dotnet test $TEST_INTG_PROJECT_NAME --configuration $BUILD_CONFIGURATION --no-build
  dependencies:
    - build

publish:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  before_script: 
    - docker info
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t "$CI_REGISTRY_IMAGE/prod:latest" . -f Prod/Dockerfile
    - docker push "$CI_REGISTRY_IMAGE/prod:latest"

deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$ENV_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan "$ENV_SSH_HOST" >> ~/.ssh/known_hosts
  script:
    - scp -o StrictHostKeyChecking=no compose.yaml "$ENV_SSH_USER@$ENV_SSH_HOST:/compose.yaml"
    - ssh -o StrictHostKeyChecking=no "$ENV_SSH_USER@$ENV_SSH_HOST" "
      echo '$CI_REGISTRY_PASSWORD' | docker login -u '$CI_REGISTRY_USER' --password-stdin '$CI_REGISTRY' &&
      docker compose down &&
      docker compose pull &&
      docker compose up -d
      "
  
