services:
  prod:
    image: prod
    env_file:
      - Prod/.env
    build:
      context: .
      dockerfile: Prod/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    env_file:
      - Prod/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 3s
      timeout: 10s
      retries: 5
volumes:
  postgres_data:
#  grafana_data:
#  prometheus_data:
