services:
  prod:
    image: gitlab.prodcontest.ru:5050/team-21/3bd/prod:latest
    env_file:
      - Prod/.env
    build:
      context: .
      dockerfile: Prod/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:8080"
  postgres:
    image: postgres:latest
    env_file:
      - Prod/.env
    ports:
      - "8050:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 3s
      timeout: 10s
      retries: 5
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "8051:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "8052:3000"
    env_file:
      - Prod/.env
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data:
  prometheus_data:
